# Site settings
title: 지도밖으로
email: enjoyhee@gmail.com
description: 소개
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  outofmap

# Build settings
markdown: kramdown
